[Definition]
failregex = ^.*sshd\[\d+\]: Connection closed by authenticating user .* <HOST> port \d+ \[preauth\]$
            ^.*sshd\[\d+\]: Failed password for .* from <HOST> port \d+ ssh2$
            ^.*sshd\[\d+\]: Invalid user .* from <HOST> port \d+$
ignoreregex =
